# Generated by Django 4.2.4 on 2023-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('communication', models.CharField(choices=[('LT', 'Lithuanian'), ('EN', 'English'), ('RU', 'Russian'), ('PL', 'Poland')], max_length=2)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
