# Generated by Django 4.2.4 on 2023-08-12 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
