# Generated by Django 4.2.4 on 2023-08-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_event_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Category',
        ),
    ]
